app:
  domain: 'http://localhost'
  port: 8080

database:
  dsn: 'host=postgres user=user password=H@55P@ssw0rd dbname=moded port=5432'

redis:
  addr: redis:6379
  password: ""
  db: 0

jwt:
  secret: '0b9b72f783d86c0068cb3650bdc9002364a6caf9'